all:
  children:
    web:
      hosts:
        server-one:
          ansible_host: 34.217.65.113
        server-two:
          ansible_host: 35.85.224.159
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ~/.ssh/aws
